FROM openjdk:8

LABEL maintainer="Abhijith.Komalachery@csaa.com"

# Installs Ant
ENV ANT_VERSION 1.10.5
RUN cd && \
    wget -q http://apache.mirrors.hoobly.com//ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz && \
    tar -xzf apache-ant-${ANT_VERSION}-bin.tar.gz && \
    mv apache-ant-${ANT_VERSION} /opt/ant && \
    rm apache-ant-${ANT_VERSION}-bin.tar.gz
ENV ANT_HOME /opt/ant
ENV PATH ${PATH}:/opt/ant/bin

COPY . src/

WORKDIR src/

RUN ant war -buildfile build.xml
